---
title: "Security Handbook"
remote_theme: pmarsceill/just-the-docs
search_enabled: false

aux_links:
  'CS':
    - "/cs/{{ page.name }}"
  'EN':
    - "/en/{{ page.name }}"

back_to_top: true
back_to_top_text: "Back to top"
